#!/usr/bin/env python
import sys
import tweepy
import string

# This information is for the @c2fo_alerts twitter account
API_KEY = '<set one up from dev.twitter.com>'
API_SECRET = '<set one up from dev.twitter.com>'
ACCESS_TOKEN = '<set one up from dev.twitter.com>'
ACCESS_TOKEN_SECRET = '<set one up from dev.twitter.com>'
auth = tweepy.OAuthHandler(API_KEY, API_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

# Process the commandline argument, replace words etc. to shorten the message
s = sys.argv[1]
s = string.replace(s,"WARNING","WARN")
s = string.replace(s,"PROBLEM","PROB")
s = string.replace(s,"CRITICAL","CRIT")

# Send the message, 140 characters max.
api.update_status(s[0:140])
